import { NgModule } from '@angular/core';
import { NZ_ICONS, NzIconModule } from 'ng-zorro-antd/icon';

import {
  MenuFoldOutline,
  MenuUnfoldOutline,
  FormOutline,
  DashboardOutline,
  MailOutline,
  LinkOutline,
  UserOutline,
  LogoutOutline,
  MedicineBoxOutline,
  SettingOutline,
  MoneyCollectOutline,
  AppstoreOutline,
  InfoCircleOutline,
  QuestionCircleOutline,
  DiffOutline,
  ContactsOutline,
  CheckSquareOutline,
  BookOutline,
  FilterOutline,
  InteractionOutline,
  InfoCircleTwoTone,
  ShareAltOutline,
  RollbackOutline,
  CheckCircleTwoTone,
  DownSquareOutline,
  BranchesOutline,
  InboxOutline,
  FlagOutline,
  ContainerOutline,
  CarryOutOutline,
  UnorderedListOutline,
  GoldOutline,
  VerticalAlignBottomOutline,
  DownloadOutline,
  MessageOutline,
  ExportOutline,
  PlusOutline,
  DeleteOutline,
  DeleteTwoTone,
  EditOutline,
  QuestionCircleFill,
  PlusCircleOutline,
  TeamOutline,
  ShoppingCartOutline,
  CameraOutline,
  HomeOutline,
  SearchOutline,
  BellOutline,
  UploadOutline,
  LockOutline
} from '@ant-design/icons-angular/icons';

const iconDefinitions = [
  MenuFoldOutline,
  MenuUnfoldOutline,
  DashboardOutline,
  FormOutline,
  MailOutline,
  EditOutline,
  DeleteTwoTone,
  PlusCircleOutline,
  QuestionCircleFill,
  LinkOutline,
  UserOutline,
  LogoutOutline,
  MedicineBoxOutline,
  SettingOutline,
  MoneyCollectOutline,
  AppstoreOutline,
  InfoCircleOutline,
  QuestionCircleOutline,
  DiffOutline,
  ContactsOutline,
  CheckSquareOutline,
  BookOutline,
  FilterOutline,
  InteractionOutline,
  InfoCircleTwoTone,
  ShareAltOutline,
  RollbackOutline,
  CheckCircleTwoTone,
  DownSquareOutline,
  BranchesOutline,
  InboxOutline,
  FlagOutline,
  ContainerOutline,
  CarryOutOutline,
  UnorderedListOutline,
  GoldOutline,
  DownloadOutline,
  MessageOutline,
  PlusOutline,
  ExportOutline,
  DeleteOutline,
  VerticalAlignBottomOutline,
  TeamOutline,
  ShoppingCartOutline,
  CameraOutline,
  HomeOutline,
  SearchOutline,
  BellOutline,
  UploadOutline,
  LockOutline
 
];

@NgModule({
  imports: [NzIconModule],
  exports: [NzIconModule],
  providers: [{ provide: NZ_ICONS, useValue: iconDefinitions }],
})
export class IconsProviderModule {}
